# Generated by Django 3.1.5 on 2022-02-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tell', models.CharField(blank=True, max_length=100, null=True)),
                ('sender', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('myself', models.BooleanField()),
            ],
        ),
    ]
